# language: php
# .scrutinizer.yml
before_commands:
    - "composer install --prefer-dist --no-interaction"

filter:
    paths:
        - src/*
        - tests/*
    excluded_paths:
        - docs/*

tools:
    external_code_coverage: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_cs_fixer:
        enabled: true
        filter:
            paths:
                - src/*
                - tests/*
            excluded_paths:
                - docs/*
        config:
            level: all
    php_cpd:
        enabled: true
        excluded_dirs:
            - docs/*
    php_loc:
        enabled: true
        excluded_dirs:
            - docs/*
    php_mess_detector:
        enabled: true
        filter:
            paths:
                - src/*
                - tests/*
    php_pdepend:
        enabled: true
        excluded_dirs:
            - docs/*
    php_analyzer: true
    php_analyzer:
        filter:
            paths:
                - src/*
                - tests/*
    sensiolabs_security_checker: true

checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
