language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update --no-interaction
  - composer --version --no-interaction

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

before_script:
  - composer update --prefer-dist $PREFER_LOWEST
  - composer --optimize-autoloader --no-interaction

script:
  - bin/phpunit -c tests/ --coverage-clover=coverage.clover --coverage-html=./docs/coverage

after_script:
  # We upload only for reference platform! This is our base for further code analyses and so on.
  - if [ $(phpenv version-name) == "5.5" ] && [ "$PREFER_LOWEST" == "--prefer-lowest" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) == "5.5" ] && [ "$PREFER_LOWEST" == "--prefer-lowest" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover > /dev/null 2>&1; fi

after_success:
  # Push coverage to github pages branch
  - chmod +x ./update-gh-pages.sh
  - if [ $(phpenv version-name) == "5.5" ] && [ "$PREFER_LOWEST" == "--prefer-lowest" ]; then bash ./update-gh-pages.sh; fi
  # CREATE GIT TAG
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git commit -m "Set build VERSION number" public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --tags --quiet https://$GITHUBKEY@github.com/clickalicious/CachingMiddleware > /dev/null 2>&1

# Blacklist the pushed tag from above to prevent black hole
branches:
  except:
    - /^build-[0-9a-z\-]*/

# Who to notify?
notifications:
  slack:
    secure: "hhJBGiLFxLgvKdSu5hIUInj4YwYBfsiPBt1NTseWWHArqhAz3YaJWGA6QBT4Wkk+RB2KD6WclqEf80ReHyQwLoWaZ3xkbtUvFgTnPDmcFGtNSECbQJA8ODvR6IwF8OCbcOioeOi+yk1VsHkRsZka5UqdYDz7zRcGXDUBpS1vtzw1w3Cc4l2pXZ6eigL7gwGULlEjRuN+dZWsUQZH2SIOeLIN6FbGI7A0KZKh/kb4k46f6dwFkZWfwUBBOg0M480olXRrM5M5spqDxx3Tf3syjgiO2IZ/3T/cdEbLnO1Qh3XYa3TMn41Mro6pEo8J9MpcyZRkOaEoemlnN0aTFew6rPOHUzF6VAzzIj4gG3gwfjBpHl0ubX1IONN1y2Mn0suu+KtCPatziDj8dWykKofkXuvYYgXHJ5vlurcSoFZPS5TBlTGeoJYCLdtV1K3OJcEENr/VM7TsxAWMqSW1/4WLxgvEFunn7eyJWzXFqsOjbn6R7C09CcGxi+T8a98/qQxJrSljV8ihyTewAtnKMAaNXQqTWBSFOIzW3Y7gNayZbBELLe3yYyV7OB73MrFz+W+srvRt9XCI2+ENh8cP4A9iim7zSd1MsEnNduhldXY5/JmfbCb7FdAdDTxpuLoSyLqZJw18L47dx3wCBbCkWyUayu14Eka82PCcKnPJd/qVrT8="
  email:
    recipients:
      - opensource@clickalicious.de
